import { api } from '../../src/modules/seriesListing/types'

/**
 * @since 09.07.2021
 *
 */
const data: api.Fetch = /*fs-start*/ {
  hits: [
    {
      title: 'Porzellan-Serie Masca',
      brand: 'VEGA',
      images: {
        imageWeb: [
          {
            url: 'pim/4af876/76b73a/38f3f6/9a3900/797dbc/d7/4af87676b73a38f3f69a3900797dbcd7.jpeg',
            classes: ['EMG'],
          },
        ],
      },
      referenceSku: {
        sku_uuid: '371ef8835cbd4ffbbedd371690ca7292',
        unitName: 'Stück',
        purchaseUnit: 6,
        referenceUnit: 1,
        packUnit: 'Packung',
        sku_title: 'Teller flach Masca',
        product_type: 'Teller flach',
        sorting: 1,
        sellable: true,
        piecePriceNet: 1,
        piecePriceGross: 1.19,
        piecePseudoPriceNet: 0,
        piecePseudoPriceGross: 0,
        referencePriceNet: null,
        referencePriceGross: null,
        piecePriceNetString: '1,00 € / Stück',
        piecePriceGrossString: '1,19 € / Stück',
        referencePriceNetString: null,
        referencePriceGrossString: null,
        ecoTaxNet: null,
        ecoTaxGross: null,
        packPriceNet: 0,
        packPriceGross: 0,
        packPseudoPriceGross: 0,
        packPseudoPriceNet: 0,
      },
      objectID: 'tellerserie-masca',
    },
    {
      title: 'Tellerserie Skady ',
      brand: 'VEGA',
      images: {
        imageWeb: [
          {
            url: 'pim/0623aa/4ec7f1/a893a7/c86387/330f10/92/0623aa4ec7f1a893a7c86387330f1092.jpeg',
            classes: ['EMG'],
          },
        ],
      },
      referenceSku: {
        sku_uuid: '12394c5237ac4cdab4029098c8ec2b49',
        unitName: 'Stück',
        purchaseUnit: 4,
        referenceUnit: 1,
        packUnit: 'Packung',
        sku_title: 'Teller mit niedrigem Rand Skady',
        product_type: 'Teller flach',
        sorting: 1,
        sellable: false,
        piecePriceNet: 3.99,
        piecePriceGross: 4.75,
        piecePseudoPriceNet: 0,
        piecePseudoPriceGross: 0,
        referencePriceNet: null,
        referencePriceGross: null,
        piecePriceNetString: '3,99 € / Stück',
        piecePriceGrossString: '4,75 € / Stück',
        referencePriceNetString: null,
        referencePriceGrossString: null,
        ecoTaxNet: null,
        ecoTaxGross: null,
        packPriceNet: 0,
        packPriceGross: 0,
        packPseudoPriceGross: 0,
        packPseudoPriceNet: 0,
      },
      objectID: 'teller-serie-skady',
    },
    {
      title: 'Porzellan-Tellerserie Laja ',
      brand: 'VEGA',
      images: {
        imageWeb: [
          {
            url: 'pim/1da17b/7a2518/6a5e24/e0040c/c1f1c0/28/1da17b7a25186a5e24e0040cc1f1c028.jpeg',
            classes: ['EMG'],
          },
        ],
      },
      referenceSku: {
        sku_uuid: '4bdaad41e2594ec2971e316ab6ee4dbc',
        unitName: 'Stück',
        purchaseUnit: 6,
        referenceUnit: 1,
        packUnit: 'Packung',
        sku_title: 'Teller flach Laja',
        product_type: 'Teller flach',
        sorting: 1,
        sellable: true,
        piecePriceNet: 0.58,
        piecePriceGross: 0.69,
        piecePseudoPriceNet: 0,
        piecePseudoPriceGross: 0,
        referencePriceNet: null,
        referencePriceGross: null,
        piecePriceNetString: '0,58 € / Stück',
        piecePriceGrossString: '0,69 € / Stück',
        referencePriceNetString: null,
        referencePriceGrossString: null,
        ecoTaxNet: null,
        ecoTaxGross: null,
        packPriceNet: 0,
        packPriceGross: 0,
        packPseudoPriceGross: 0,
        packPseudoPriceNet: 0,
      },
      objectID: 'teller-serie-laja',
    },
    {
      title: 'Porzellan-Tellerserie Kelda',
      brand: 'VEGA',
      images: {
        imageWeb: [
          {
            url: 'pim/a4984e/476373/d2b53d/6b7aac/0c65d5/cc/a4984e476373d2b53d6b7aac0c65d5cc.jpeg',
            classes: ['EMG'],
          },
        ],
      },
      referenceSku: {
        sku_uuid: '2b63b960cbe041feaef8b4d4eed162c3',
        unitName: 'Stück',
        purchaseUnit: 4,
        referenceUnit: 1,
        packUnit: 'Packung',
        sku_title: 'Servierschaufel Kelda rechteckig',
        product_type: 'Teller tief',
        sorting: 1,
        sellable: true,
        piecePriceNet: 2.75,
        piecePriceGross: 3.27,
        piecePseudoPriceNet: 0,
        piecePseudoPriceGross: 0,
        referencePriceNet: null,
        referencePriceGross: null,
        piecePriceNetString: '2,75 € / Stück',
        piecePriceGrossString: '3,27 € / Stück',
        referencePriceNetString: null,
        referencePriceGrossString: null,
        ecoTaxNet: null,
        ecoTaxGross: null,
        packPriceNet: 0,
        packPriceGross: 0,
        packPseudoPriceGross: 0,
        packPseudoPriceNet: 0,
      },
      objectID: 'teller-serie-kelda',
    },
    {
      title: 'Porzellan-Serie Mixor',
      brand: 'VEGA',
      images: {
        imageWeb: [
          {
            url: 'pim/3a74d2/2c6a55/5d8088/ca0d50/d11cb3/6e/3a74d22c6a555d8088ca0d50d11cb36e.jpeg',
            classes: ['EMG'],
          },
        ],
      },
      referenceSku: {
        sku_uuid: '0f877f7207b541f3afd51649c4e015d7',
        unitName: 'Stück',
        purchaseUnit: 6,
        referenceUnit: 1,
        packUnit: 'Packung',
        sku_title: 'Teller flach Mixor',
        product_type: 'Teller flach',
        sorting: 1,
        sellable: true,
        piecePriceNet: 0.67,
        piecePriceGross: 0.79,
        piecePseudoPriceNet: 0,
        piecePseudoPriceGross: 0,
        referencePriceNet: null,
        referencePriceGross: null,
        piecePriceNetString: '0,67 € / Stück',
        piecePriceGrossString: '0,79 € / Stück',
        referencePriceNetString: null,
        referencePriceGrossString: null,
        ecoTaxNet: null,
        ecoTaxGross: null,
        packPriceNet: 0,
        packPriceGross: 0,
        packPseudoPriceGross: 0,
        packPseudoPriceNet: 0,
      },
      objectID: 'porzellan-serie-mixor',
    },
    {
      title: 'Porzellan-Serie Liron',
      brand: 'VEGA',
      images: {
        imageWeb: [
          {
            url: 'pim/81be30/793d8a/b1f365/544c56/50c290/8f/81be30793d8ab1f365544c5650c2908f.jpeg',
            classes: ['EMG'],
          },
        ],
      },
      referenceSku: {
        sku_uuid: '3ac3f8edddbd42babd571990ddaf19c3',
        unitName: 'Stück',
        purchaseUnit: 6,
        referenceUnit: 1,
        packUnit: 'Packung',
        sku_title: 'Teller flach Liron',
        product_type: 'Teller flach',
        sorting: 1,
        sellable: true,
        piecePriceNet: 0.75,
        piecePriceGross: 0.89,
        piecePseudoPriceNet: 0,
        piecePseudoPriceGross: 0,
        referencePriceNet: null,
        referencePriceGross: null,
        piecePriceNetString: '0,75 € / Stück',
        piecePriceGrossString: '0,89 € / Stück',
        referencePriceNetString: null,
        referencePriceGrossString: null,
        ecoTaxNet: null,
        ecoTaxGross: null,
        packPriceNet: 0,
        packPriceGross: 0,
        packPseudoPriceGross: 0,
        packPseudoPriceNet: 0,
      },
      objectID: 'porzellan-serie-liron',
    },
    {
      title: 'Porzellan-Serie Limaro',
      brand: 'VEGA',
      images: {
        imageWeb: [
          {
            url: 'pim/6ab3d3/a93268/6184b7/b5ed76/144d6e/28/6ab3d3a932686184b7b5ed76144d6e28.jpeg',
            classes: ['EMG'],
          },
        ],
      },
      referenceSku: {
        sku_uuid: '81a0802b3d324206b790a1f8c875c9a6',
        unitName: 'Stück',
        purchaseUnit: 6,
        referenceUnit: 1,
        packUnit: 'Packung',
        sku_title: 'Teller flach Limaro',
        product_type: 'Teller flach',
        sorting: 1,
        sellable: true,
        piecePriceNet: 1.17,
        piecePriceGross: 1.39,
        piecePseudoPriceNet: 0,
        piecePseudoPriceGross: 0,
        referencePriceNet: null,
        referencePriceGross: null,
        piecePriceNetString: '1,17 € / Stück',
        piecePriceGrossString: '1,39 € / Stück',
        referencePriceNetString: null,
        referencePriceGrossString: null,
        ecoTaxNet: null,
        ecoTaxGross: null,
        packPriceNet: 0,
        packPriceGross: 0,
        packPseudoPriceGross: 0,
        packPseudoPriceNet: 0,
      },
      objectID: 'porzellan-serie-limaci',
    },
    {
      title: 'Porzellan-Serie Alessia',
      brand: 'VEGA',
      images: {
        imageWeb: [
          {
            url: 'pim/0cd40e/0b6455/cc62c0/c71800/1c0869/6e/0cd40e0b6455cc62c0c718001c08696e.jpeg',
            classes: ['EMG'],
          },
        ],
      },
      referenceSku: {
        sku_uuid: 'b712b9b836824bb99061902bd07a4ef6',
        unitName: 'Stück',
        purchaseUnit: 6,
        referenceUnit: 1,
        packUnit: 'Packung',
        sku_title: 'Teller flach Alessia',
        product_type: 'Teller flach',
        sorting: 1,
        sellable: true,
        piecePriceNet: 0.92,
        piecePriceGross: 1.09,
        piecePseudoPriceNet: 0,
        piecePseudoPriceGross: 0,
        referencePriceNet: null,
        referencePriceGross: null,
        piecePriceNetString: '0,92 € / Stück',
        piecePriceGrossString: '1,09 € / Stück',
        referencePriceNetString: null,
        referencePriceGrossString: null,
        ecoTaxNet: null,
        ecoTaxGross: null,
        packPriceNet: 0,
        packPriceGross: 0,
        packPseudoPriceGross: 0,
        packPseudoPriceNet: 0,
      },
      objectID: 'porzellan-serie-alessia',
    },
    {
      title: 'Hartglas-Serie Ashley',
      brand: 'VEGA',
      images: {
        imageWeb: [
          {
            url: 'pim/c2298b/a60648/a61141/dc5054/417ea8/6c/c2298ba60648a61141dc5054417ea86c.jpeg',
            classes: ['EMG'],
          },
        ],
      },
      referenceSku: {
        sku_uuid: 'cabf7dedf4534ac9aefc2beb36dd827c',
        unitName: 'Stück',
        purchaseUnit: 6,
        referenceUnit: 1,
        packUnit: 'Packung',
        sku_title: 'Teller flach Ashley',
        product_type: 'Teller flach',
        sorting: 1,
        sellable: false,
        piecePriceNet: 1.59,
        piecePriceGross: 1.89,
        piecePseudoPriceNet: 0,
        piecePseudoPriceGross: 0,
        referencePriceNet: null,
        referencePriceGross: null,
        piecePriceNetString: '1,59 € / Stück',
        piecePriceGrossString: '1,89 € / Stück',
        referencePriceNetString: null,
        referencePriceGrossString: null,
        ecoTaxNet: null,
        ecoTaxGross: null,
        packPriceNet: 0,
        packPriceGross: 0,
        packPseudoPriceGross: 0,
        packPseudoPriceNet: 0,
      },
      objectID: 'hartglas-serie-ashley',
    },
  ],
  nbPages: 1,
  categoryTree: [],
  page: 1,
  nbHits: 10,
} /*fs-end*/
export default data
