export const SET: 'cart/SET' = 'cart/SET'
export const REFRESH: 'cart/REFRESH' = 'cart/REFRESH'
export const ADD_ITEM_REQUEST: 'cart/ADD_ITEM_REQUEST' = 'cart/ADD_ITEM_REQUEST'
export const ADD_ITEM_SUCCESS: 'cart/ADD_ITEM_SUCCESS' = 'cart/ADD_ITEM_SUCCESS'
export const ADD_ITEM_FAILURE: 'cart/ADD_ITEM_FAILURE' = 'cart/ADD_ITEM_FAILURE'
export const REMOVE_ITEM_REQUEST: 'cart/REMOVE_ITEM_REQUEST' =
  'cart/REMOVE_ITEM_REQUEST'
export const REMOVE_ITEM_SUCCESS: 'cart/REMOVE_ITEM_SUCCESS' =
  'cart/REMOVE_ITEM_SUCCESS'
export const REMOVE_ITEM_FAILURE: 'cart/REMOVE_ITEM_FAILURE' =
  'cart/REMOVE_ITEM_FAILURE'
