export const SET_SEARCH_VALUE: 'ui/SET_SEARCH_VALUE' = 'ui/SET_SEARCH_VALUE'
export const TOGGLE_NAVI: 'ui/TOGGLE_NAVI' = 'ui/TOGGLE_NAVI'
export const SET_SIDEBAR_CATEGORY: 'ui/SET_SIDEBAR_CATEGORY' =
  'ui/SET_SIDEBAR_CATEGORY'
export const SET_CURRENT_CATEGORY: 'ui/SET_CURRENT_CATEGORY' =
  'ui/SET_CURRENT_CATEGORY'
export const CLEAR: 'ui/CLEAR' = 'ui/CLEAR'
export const SET_MODAL_CONTENT: 'ui/SET_MODAL_CONTENT' = 'ui/SET_MODAL_CONTENT'
export const SHOW_OVERLAY: 'b2cSwitch/SHOW_OVERLAY' = 'b2cSwitch/SHOW_OVERLAY'
export const HIDE_OVERLAY: 'b2cSwitch/HIDE_OVERLAY' = 'b2cSwitch/HIDE_OVERLAY'
